-- hivra_agents guards: RE-ARM (companion to HIVRA-AGENTS-GUARDS-DOWN-PLAN.sql)
--
-- Puts back exactly the triggers and CHECK constraints the down plan dropped, with
-- the definitions the chain created (captured by the rehearsal harness after the
-- chain ran on a SYNTHETIC production-shaped schema, then re-applied and compared:
-- the guard set was identical). Never auto-applied; owner only.
--
-- Re-adding a CHECK constraint validates EVERY existing row. Rows the old build
-- wrote while the guards were off may violate them; if the script fails nothing
-- changes (one transaction), and the error names the constraint to repair.
-- Run it before putting the new build back in front of the table.
--
-- Generated with: node scripts/release/prod-chain-rehearsal.mjs ... --emit-rearm
begin;
set local lock_timeout = '5s';
alter table public.hivra_agents drop constraint if exists hivra_agents_binding_token_hash_check;
alter table public.hivra_agents add constraint hivra_agents_binding_token_hash_check CHECK ((infrastructure_binding_token_hash ~ '^[0-9a-f]{64}$'::text));
alter table public.hivra_agents drop constraint if exists hivra_agents_canary_provisioner_binding_check;
alter table public.hivra_agents add constraint hivra_agents_canary_provisioner_binding_check CHECK (((managed_provisioner_channel <> 'canary'::text) OR ((NOT (deployment_mode IS DISTINCT FROM 'hivra-managed'::text)) AND (NOT (computer_substrate IS DISTINCT FROM 'proxmox-kvm'::text)))));
alter table public.hivra_agents drop constraint if exists hivra_agents_computer_substrate_check;
alter table public.hivra_agents add constraint hivra_agents_computer_substrate_check CHECK ((computer_substrate = ANY (ARRAY['proxmox-kvm'::text, 'provider-vm'::text, 'gvisor'::text, 'do-managed-session'::text])));
alter table public.hivra_agents drop constraint if exists hivra_agents_cpu_max_valid;
alter table public.hivra_agents add constraint hivra_agents_cpu_max_valid CHECK (((cpu_max IS NULL) OR (((cpu_max)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])) AND (cpu_max > (0)::numeric) AND (cpu_max >= cpu))));
alter table public.hivra_agents drop constraint if exists hivra_agents_deployment_authority_matrix_check;
alter table public.hivra_agents add constraint hivra_agents_deployment_authority_matrix_check CHECK ((((deployment_mode = 'hivra-managed'::text) AND (infrastructure_connection_id IS NULL) AND (deployment_target_id IS NULL) AND (infrastructure_connection_revision IS NULL) AND (proxmox_host <> '__hivra_self_managed_no_ambient_authority__'::text)) OR ((deployment_mode = 'self-managed'::text) AND (proxmox_host = '__hivra_self_managed_no_ambient_authority__'::text) AND (((status <> 'deleted'::text) AND infrastructure_binding_token_enforced AND (infrastructure_connection_id IS NOT NULL) AND (deployment_target_id IS NOT NULL) AND (infrastructure_connection_revision IS NOT NULL)) OR ((status = 'deleted'::text) AND (infrastructure_connection_id IS NULL) AND (deployment_target_id IS NULL) AND (infrastructure_connection_revision IS NULL))))));
alter table public.hivra_agents drop constraint if exists hivra_agents_deployment_mode_check;
alter table public.hivra_agents add constraint hivra_agents_deployment_mode_check CHECK ((deployment_mode = ANY (ARRAY['hivra-managed'::text, 'self-managed'::text])));
alter table public.hivra_agents drop constraint if exists hivra_agents_desired_state_check;
alter table public.hivra_agents add constraint hivra_agents_desired_state_check CHECK ((desired_state = ANY (ARRAY['running'::text, 'stopped'::text, 'deleted'::text])));
alter table public.hivra_agents drop constraint if exists hivra_agents_do_session_identity_check;
alter table public.hivra_agents add constraint hivra_agents_do_session_identity_check CHECK (((((computer_substrate <> 'do-managed-session'::text) AND (do_session_name IS NULL) AND (do_session_id IS NULL) AND (do_session_harness IS NULL) AND (do_session_size IS NULL) AND (do_launch_request_id IS NULL) AND (do_session_observation IS NULL) AND (do_cleanup_receipt IS NULL)) OR ((computer_substrate = 'do-managed-session'::text) AND (deployment_mode = 'self-managed'::text) AND (vmid IS NULL) AND (provider_capacity_order_id IS NULL) AND (provider_enrollment_attempt_id IS NULL) AND (provider_server_id IS NULL) AND (gvisor_sandbox_id IS NULL) AND (computer_profile IS NULL) AND (infrastructure_binding_token_enforced IS TRUE) AND (do_launch_request_id IS NOT NULL) AND (do_session_name = ('hivra-'::text || replace((id)::text, '-'::text, ''::text))) AND ((do_session_id IS NULL) OR (do_session_id ~ '^[A-Za-z0-9_.:-]{1,128}$'::text)) AND (((do_session_harness = 'claude-code'::text) AND (type = 'claude-code'::text)) OR ((do_session_harness = 'codex'::text) AND (type = 'codex'::text)) OR ((do_session_harness = 'hermes'::text) AND (type = 'hermes'::text))) AND (do_session_size = ANY (ARRAY['mars-1vcpu-1gb'::text, 'mars-2vcpu-2gb'::text, 'mars-2vcpu-4gb'::text, 'mars-4vcpu-8gb'::text, 'mars-16vcpu-32gb'::text])) AND ((do_session_observation IS NULL) OR (jsonb_typeof(do_session_observation) = 'object'::text)) AND (((status <> 'deleted'::text) AND (do_cleanup_receipt IS NULL) AND (infrastructure_connection_id IS NOT NULL) AND (deployment_target_id IS NOT NULL) AND (infrastructure_connection_revision IS NOT NULL)) OR ((status = 'deleted'::text) AND (infrastructure_connection_id IS NULL) AND (deployment_target_id IS NULL) AND (infrastructure_connection_revision IS NULL) AND (jsonb_typeof(do_cleanup_receipt) = 'object'::text) AND (((do_cleanup_receipt ->> 'state'::text) = ANY (ARRAY['absent'::text, 'never-created'::text])) OR (((do_cleanup_receipt ->> 'state'::text) = 'forgotten'::text) AND ((do_cleanup_receipt ->> 'acknowledgedAt'::text) IS NOT NULL))) AND ((do_cleanup_receipt ->> 'sessionName'::text) = do_session_name))) AND (operation_id IS NULL))) IS TRUE));
alter table public.hivra_agents drop constraint if exists hivra_agents_gvisor_observation_check;
alter table public.hivra_agents add constraint hivra_agents_gvisor_observation_check CHECK (((computer_substrate <> 'gvisor'::text) OR (((gvisor_observation IS NULL) OR ((jsonb_typeof(gvisor_observation) = 'object'::text) AND ((gvisor_observation ->> 'computerId'::text) = (id)::text) AND ((gvisor_observation ->> 'sandboxId'::text) = (gvisor_sandbox_id)::text) AND (((gvisor_observation ->> 'state'::text) = 'absent'::text) OR (((gvisor_observation ->> 'isolationClass'::text) = 'application-kernel'::text) AND ((gvisor_observation ->> 'isolationDriver'::text) = 'gvisor-runsc'::text) AND ((gvisor_observation ->> 'runtime'::text) = 'runsc'::text) AND ((gvisor_observation ->> 'reservationEqualsMaximum'::text) = 'true'::text))))) AND ((gvisor_cleanup_receipt IS NULL) OR ((jsonb_typeof(gvisor_cleanup_receipt) = 'object'::text) AND ((gvisor_cleanup_receipt ->> 'computerId'::text) = (id)::text) AND ((gvisor_cleanup_receipt ->> 'sandboxId'::text) = (gvisor_sandbox_id)::text) AND ((gvisor_cleanup_receipt ->> 'state'::text) = 'absent'::text))) AND ((status <> 'deleted'::text) OR ((jsonb_typeof((gvisor_cleanup_receipt -> 'binding'::text)) = 'object'::text) AND (((gvisor_cleanup_receipt -> 'binding'::text) ->> 'connectionId'::text) ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'::text) AND (((gvisor_cleanup_receipt -> 'binding'::text) ->> 'targetId'::text) ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'::text) AND ((((gvisor_cleanup_receipt -> 'binding'::text) ->> 'connectionRevision'::text))::bigint > 0) AND (((gvisor_cleanup_receipt -> 'binding'::text) ->> 'adapterSha256'::text) = gvisor_adapter_sha256) AND (((gvisor_cleanup_receipt -> 'binding'::text) ->> 'runtimeSha256'::text) = gvisor_runtime_sha256))))));
alter table public.hivra_agents drop constraint if exists hivra_agents_managed_provisioner_channel_check;
alter table public.hivra_agents add constraint hivra_agents_managed_provisioner_channel_check CHECK ((managed_provisioner_channel = ANY (ARRAY['default'::text, 'canary'::text])));
alter table public.hivra_agents drop constraint if exists hivra_agents_operation_shape_check;
alter table public.hivra_agents add constraint hivra_agents_operation_shape_check CHECK ((((operation_id IS NULL) AND (operation_kind IS NULL) AND (operation_started_at IS NULL) AND (operation_payload IS NULL)) OR ((operation_id IS NOT NULL) AND (operation_kind = ANY (ARRAY['provision'::text, 'start'::text, 'stop'::text, 'restart'::text, 'resize'::text, 'snapshot'::text, 'restore'::text, 'delete'::text, 'desktop_prepare'::text, 'agent_attach'::text, 'private_access'::text, 'agent_access_change'::text, 'agent_detach'::text])) AND (operation_kind IS NOT NULL) AND (operation_started_at IS NOT NULL) AND ((operation_payload IS NULL) OR (jsonb_typeof(operation_payload) = 'object'::text)))));
alter table public.hivra_agents drop constraint if exists hivra_agents_provider_identity_check;
alter table public.hivra_agents add constraint hivra_agents_provider_identity_check CHECK (((((computer_substrate = 'proxmox-kvm'::text) AND (provider_capacity_order_id IS NULL) AND (provider_enrollment_attempt_id IS NULL) AND (provider_server_id IS NULL) AND (gvisor_sandbox_id IS NULL) AND (gvisor_adapter_version IS NULL) AND (gvisor_adapter_sha256 IS NULL) AND (gvisor_runtime_sha256 IS NULL)) OR ((computer_substrate = 'provider-vm'::text) AND (deployment_mode = 'self-managed'::text) AND (vmid IS NULL) AND (provider_capacity_order_id IS NOT NULL) AND (provider_enrollment_attempt_id IS NOT NULL) AND (provider_server_id ~ '^[1-9][0-9]{0,15}$'::text) AND ((provider_server_id)::numeric <= ('9007199254740991'::bigint)::numeric) AND (gvisor_sandbox_id IS NULL) AND (gvisor_adapter_version IS NULL) AND (gvisor_adapter_sha256 IS NULL) AND (gvisor_runtime_sha256 IS NULL)) OR ((computer_substrate = 'gvisor'::text) AND (deployment_mode = 'self-managed'::text) AND (vmid IS NULL) AND (provider_capacity_order_id IS NULL) AND (provider_enrollment_attempt_id IS NULL) AND (provider_server_id IS NULL) AND (gvisor_sandbox_id IS NOT NULL) AND (gvisor_adapter_version = '2026.09.15.1'::text) AND (gvisor_adapter_sha256 ~ '^[0-9a-f]{64}$'::text) AND (gvisor_runtime_sha256 ~ '^[0-9a-f]{64}$'::text) AND (computer_profile = 'linux-terminal'::text) AND (type = 'linux-terminal'::text) AND (cpu_max = cpu) AND (ram_max = ram) AND (((status <> 'deleted'::text) AND (infrastructure_connection_id IS NOT NULL) AND (deployment_target_id IS NOT NULL) AND (infrastructure_connection_revision IS NOT NULL)) OR ((status = 'deleted'::text) AND (infrastructure_connection_id IS NULL) AND (deployment_target_id IS NULL) AND (infrastructure_connection_revision IS NULL) AND (((gvisor_cleanup_receipt -> 'binding'::text) ->> 'adapterSha256'::text) = gvisor_adapter_sha256) AND (((gvisor_cleanup_receipt -> 'binding'::text) ->> 'runtimeSha256'::text) = gvisor_runtime_sha256))) AND (infrastructure_binding_token_enforced IS TRUE)) OR ((computer_substrate = 'do-managed-session'::text) AND (deployment_mode = 'self-managed'::text) AND (vmid IS NULL) AND (provider_capacity_order_id IS NULL) AND (provider_enrollment_attempt_id IS NULL) AND (provider_server_id IS NULL) AND (gvisor_sandbox_id IS NULL) AND (gvisor_adapter_version IS NULL) AND (gvisor_adapter_sha256 IS NULL) AND (gvisor_runtime_sha256 IS NULL))) IS TRUE));
alter table public.hivra_agents drop constraint if exists hivra_agents_provider_install_shape_check;
alter table public.hivra_agents add constraint hivra_agents_provider_install_shape_check CHECK (((((provider_install_identity IS NULL) AND (provider_install_dispatched_at IS NULL) AND (provider_install_stopped_at IS NULL) AND (provider_install_outcome IS NULL)) OR ((computer_substrate = 'provider-vm'::text) AND (provider_install_identity IS NOT NULL) AND (provider_install_dispatched_at IS NOT NULL) AND (((provider_install_stopped_at IS NULL) AND (provider_install_outcome IS NULL)) OR ((provider_install_stopped_at >= provider_install_dispatched_at) AND (provider_install_outcome = ANY (ARRAY['cancelled'::text, 'failed'::text, 'succeeded'::text])))))) IS TRUE));
alter table public.hivra_agents drop constraint if exists hivra_agents_ram_max_valid;
alter table public.hivra_agents add constraint hivra_agents_ram_max_valid CHECK (((ram_max IS NULL) OR ((ram_max > 0) AND (ram_max >= ram))));
alter table public.hivra_agents drop constraint if exists hivra_agents_windows_iso_source_check;
alter table public.hivra_agents add constraint hivra_agents_windows_iso_source_check CHECK (((windows_iso_source IS NULL) OR (windows_iso_source = ANY (ARRAY['unknown'::text, 'windows-11'::text, 'windows-server-evaluation'::text]))));
alter table public.hivra_agents drop constraint if exists hivra_provider_desktop_access_shape;
alter table public.hivra_agents add constraint hivra_provider_desktop_access_shape CHECK ((((((provider_install_identity -> 'version'::text) = '3'::jsonb) IS TRUE) = (provider_install_desktop_access IS NOT NULL)) AND ((provider_install_desktop_access IS NULL) OR hivra_provider_desktop_access_valid(provider_install_desktop_access))));
alter table public.hivra_agents drop constraint if exists hivra_provider_native_access_shape;
alter table public.hivra_agents add constraint hivra_provider_native_access_shape CHECK ((((((provider_install_identity -> 'version'::text) = '2'::jsonb) IS TRUE) = (provider_install_native_access IS NOT NULL)) AND ((provider_install_native_access IS NULL) OR hivra_provider_native_access_valid(provider_install_native_access))));
alter table public.hivra_agents drop constraint if exists hivra_provider_native_running_no_api_token;
alter table public.hivra_agents add constraint hivra_provider_native_running_no_api_token CHECK (((NOT (((provider_install_identity -> 'version'::text) = '2'::jsonb) AND (status = 'running'::text))) OR ((api_token IS NULL) AND (chat_url IS NOT NULL) AND (ip IS NOT NULL) AND (chat_url = ('https://'::text || (provider_install_native_access ->> 'hostname'::text))) AND hivra_provider_native_access_matches(provider_install_native_access, hivra_agents.*))));
drop trigger if exists a_hivra_agents_operation_compatibility on public.hivra_agents;
CREATE TRIGGER a_hivra_agents_operation_compatibility BEFORE INSERT OR UPDATE OF status ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION normalize_hivra_agent_operation_compatibility();
drop trigger if exists hivra_agent_attachment_lease_guard on public.hivra_agents;
CREATE TRIGGER hivra_agent_attachment_lease_guard BEFORE UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_agent_attachment_lease();
drop trigger if exists hivra_agent_attachment_operation_lease_guard on public.hivra_agents;
CREATE TRIGGER hivra_agent_attachment_operation_lease_guard BEFORE UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_agent_attachment_operation_lease();
drop trigger if exists hivra_agents_deployment_authority_guard on public.hivra_agents;
CREATE TRIGGER hivra_agents_deployment_authority_guard BEFORE INSERT OR UPDATE OF user_id, status, deployment_mode, infrastructure_connection_id, deployment_target_id, infrastructure_connection_revision, proxmox_host, computer_substrate ON public.hivra_agents FOR EACH ROW WHEN ((new.computer_substrate = 'proxmox-kvm'::text)) EXECUTE FUNCTION enforce_hivra_agent_deployment_authority();
drop trigger if exists hivra_agents_detach_on_computer_delete on public.hivra_agents;
CREATE TRIGGER hivra_agents_detach_on_computer_delete AFTER UPDATE OF status ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION detach_hivra_agents_on_computer_delete();
drop trigger if exists hivra_agents_managed_provisioner_channel_guard on public.hivra_agents;
CREATE TRIGGER hivra_agents_managed_provisioner_channel_guard BEFORE UPDATE OF managed_provisioner_channel ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_managed_provisioner_channel();
drop trigger if exists hivra_agents_provider_desktop_access_guard on public.hivra_agents;
CREATE TRIGGER hivra_agents_provider_desktop_access_guard BEFORE INSERT OR UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_provider_desktop_access();
drop trigger if exists hivra_agents_provider_desktop_lifecycle_guard on public.hivra_agents;
CREATE TRIGGER hivra_agents_provider_desktop_lifecycle_guard BEFORE INSERT OR UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_provider_desktop_lifecycle();
drop trigger if exists hivra_agents_provider_installer_guard on public.hivra_agents;
CREATE TRIGGER hivra_agents_provider_installer_guard BEFORE INSERT OR UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_provider_installer();
drop trigger if exists hivra_agents_provider_native_access_guard on public.hivra_agents;
CREATE TRIGGER hivra_agents_provider_native_access_guard BEFORE INSERT OR UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_provider_native_access();
drop trigger if exists hivra_agents_provider_ownership_guard on public.hivra_agents;
CREATE TRIGGER hivra_agents_provider_ownership_guard BEFORE INSERT OR DELETE OR UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_provider_agent();
drop trigger if exists hivra_desktop_prepare_lease_guard on public.hivra_agents;
CREATE TRIGGER hivra_desktop_prepare_lease_guard BEFORE UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_desktop_prepare_lease();
drop trigger if exists hivra_do_managed_session_guard on public.hivra_agents;
CREATE TRIGGER hivra_do_managed_session_guard BEFORE INSERT OR DELETE OR UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_do_managed_session();
drop trigger if exists hivra_gvisor_computer_guard on public.hivra_agents;
CREATE TRIGGER hivra_gvisor_computer_guard BEFORE INSERT OR DELETE OR UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_gvisor_computer();
drop trigger if exists hivra_private_access_lease_guard on public.hivra_agents;
CREATE TRIGGER hivra_private_access_lease_guard BEFORE UPDATE ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_private_access_lease();
drop trigger if exists hivra_restore_while_attached_guard on public.hivra_agents;
CREATE TRIGGER hivra_restore_while_attached_guard BEFORE UPDATE OF operation_kind ON public.hivra_agents FOR EACH ROW EXECUTE FUNCTION guard_hivra_restore_while_attached();
commit;
