import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Link as LinkIcon } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import PublicSite from "@/components/public-site/PublicSite";
import { Breadcrumbs, EditorialMarkdownLink } from "@/components/public-editorial/Editorial";
import styles from "../../components/public-editorial/secondary-site.module.css";
import StructuredData from "@/components/StructuredData";
import { buildWebsiteMetadata } from "@/lib/metadata";
import { OG_IMAGE } from "@/lib/og-meta";
import { SITE_URL } from "@/lib/seo-urls";
import { readChangelog, type ChangelogEntry } from "@/lib/changelog";
import { CHANGELOG_FEED_TITLE } from "@/lib/changelog-rss";

const CHANGELOG_URL = `${SITE_URL}/changelog`;
const CHANGELOG_FEED_URL = `${CHANGELOG_URL}/rss.xml`;
const TITLE = "Changelog — what shipped on Hivra";
const DESCRIPTION =
  "Dated entries for every notable change to Hivra: bug fixes, feature ships, upstream syncs, and infrastructure work.";

const websiteMetadata = buildWebsiteMetadata({
  path: "/changelog",
  title: "Changelog | Hivra",
  description: DESCRIPTION,
  // Branded dynamic OG card generated by app/changelog/opengraph-image.tsx (#public-og-images).
  images: [OG_IMAGE.changelog],
});

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  ...websiteMetadata,
  // Preserve the canonical from buildWebsiteMetadata, add RSS auto-discovery so
  // feed readers and browsers find /changelog/rss.xml from the page head.
  alternates: {
    ...websiteMetadata.alternates,
    types: {
      "application/rss+xml": [{ url: CHANGELOG_FEED_URL, title: CHANGELOG_FEED_TITLE }],
    },
  },
};

function formatDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

function EntryBlock({ entry }: { entry: ChangelogEntry }) {
  return <article id={entry.date} className={styles.changeEntry}><header><a href={`#${entry.date}`} aria-label={`Permalink to ${entry.date} entry`} className={styles.eyebrow}><LinkIcon size={13} aria-hidden="true" /><time dateTime={entry.date}>{formatDate(entry.date)}</time></a><h2>{entry.title}</h2></header><div className={styles.articleBody}><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ a: ({ node, ...props }) => { void node; return <EditorialMarkdownLink {...props} />; } }}>{entry.body}</ReactMarkdown></div></article>;
}

export default function ChangelogPage() {
  const { lastUpdated, entries } = readChangelog();

  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
          { "@type": "ListItem", position: 2, name: "Changelog", item: CHANGELOG_URL },
        ],
      },
      {
        "@type": "WebPage",
        "@id": `${CHANGELOG_URL}#webpage`,
        url: CHANGELOG_URL,
        name: TITLE,
        description: DESCRIPTION,
        isPartOf: { "@id": `${SITE_URL}/#website` },
        ...(lastUpdated ? { dateModified: lastUpdated } : {}),
      },
    ],
  };

  return <PublicSite className={styles.page} data-page="changelog"><StructuredData schema={schema} /><main className={styles.main} id="main-content"><Breadcrumbs items={[{ label: "Changelog" }]} /><header className={styles.masthead}><span className={styles.eyebrow}>Changelog</span><h1>What shipped on Hivra</h1><p>Dated notes on every notable change to Hivra — bug fixes, feature ships, upstream syncs, and infrastructure work.</p>{lastUpdated ? <div className={styles.metadata}>Last updated <time dateTime={lastUpdated}>{formatDate(lastUpdated)}</time></div> : null}<div className={styles.changeLinks}><Link href="/roadmap">Roadmap <ArrowUpRight size={17} aria-hidden="true" /></Link><a href="/changelog/rss.xml">RSS feed <ArrowUpRight size={17} aria-hidden="true" /></a><Link href="/get-started?plan=operator">Deploy Now <ArrowUpRight size={17} aria-hidden="true" /></Link></div></header>{entries.length > 0 ? entries.map((entry) => <EntryBlock key={entry.date} entry={entry} />) : <p>No changelog entries yet.</p>}</main></PublicSite>;
}
