import PublicSite from "@/components/public-site/PublicSite";
import { Breadcrumbs, EditorialArt, EditorialQuestions, EditorialRelated } from "@/components/public-editorial/Editorial";
import ArticleNavigation from "@/components/public-editorial/ArticleNavigation.client";
import styles from "../../../components/public-editorial/secondary-site.module.css";
import agentStyles from "../agents.module.css";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowUpRight, CheckCircle } from "lucide-react";
import StructuredData from "@/components/StructuredData";
import { buildWebsiteMetadata } from "@/lib/metadata";
import { SITE_URL } from "@/lib/seo-urls";
import {
  AGENT_OFFER_PRICE_USD,
  AGENT_SEO_ENTRIES,
  PRICING_HREF,
  agentDeployHref,
  getAgentSeoEntry,
} from "@/lib/hivra/agent-seo-catalog";
import { getAgent } from "@/lib/hivra/agent-catalog";
import { BLOG_ARTICLES } from "@/lib/blog-data";

interface AgentPageParams {
  params: Promise<{ slug: string }>;
}

// Only the catalog's slugs exist; anything else is a real 404.
export const dynamicParams = false;

export function generateStaticParams() {
  return AGENT_SEO_ENTRIES.map((entry) => ({ slug: entry.slug }));
}

export async function generateMetadata({ params }: AgentPageParams): Promise<Metadata> {
  const { slug } = await params;
  const entry = getAgentSeoEntry(slug);
  const agent = entry ? getAgent(entry.slug) : undefined;
  if (!entry || !agent) return {};

  // The root layout's title template appends " | Hivra".
  return {
    title: entry.metaTitle,
    description: entry.metaDescription,
    ...buildWebsiteMetadata({
      path: `/agents/${entry.slug}`,
      title: entry.metaTitle,
      description: entry.metaDescription,
      // Generated by app/agents/[slug]/opengraph-image.tsx.
      images: [
        {
          url: `/agents/${entry.slug}/opengraph-image`,
          width: 1200,
          height: 630,
          alt: `${agent.name} on Hivra`,
          type: "image/png",
        },
      ],
    }),
  };
}

function relatedBlogTitle(slug: string): string {
  return BLOG_ARTICLES[slug]?.title ?? slug;
}

export default async function AgentPage({ params }: AgentPageParams) {
  const { slug } = await params;
  const entry = getAgentSeoEntry(slug);
  const agent = entry ? getAgent(entry.slug) : undefined;
  if (!entry || !agent) notFound();

  const pageUrl = `${SITE_URL}/agents/${entry.slug}`;
  const deployHref = agentDeployHref(entry);
  const position = AGENT_SEO_ENTRIES.findIndex((other) => other.slug === entry.slug) + 1;

  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "SoftwareApplication",
        name: `${agent.name} on Hivra`,
        applicationCategory: "DeveloperApplication",
        operatingSystem: "Web",
        description: entry.metaDescription,
        url: pageUrl,
        // The price is monthly, so the Offer says so. There is deliberately no
        // aggregateRating or review: Hivra publishes none, and inventing one is
        // worse than these pages not qualifying for Software App rich results.
        offers: {
          "@type": "Offer",
          price: AGENT_OFFER_PRICE_USD,
          priceCurrency: "USD",
          priceSpecification: {
            "@type": "UnitPriceSpecification",
            price: AGENT_OFFER_PRICE_USD,
            priceCurrency: "USD",
            unitText: "MONTH",
            billingDuration: "P1M",
          },
          url: `${SITE_URL}${deployHref}`,
        },
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
          { "@type": "ListItem", position: 2, name: "Agents", item: `${SITE_URL}/agents` },
          { "@type": "ListItem", position: 3, name: agent.name, item: pageUrl },
        ],
      },
      {
        "@type": "FAQPage",
        mainEntity: entry.faqs.map(({ q, a }) => ({
          "@type": "Question",
          name: q,
          acceptedAnswer: { "@type": "Answer", text: a },
        })),
      },
    ],
  };

  const contents = [
    { id: "overview", label: `${agent.name} on Hivra` },
    { id: "what-you-get", label: "What you get" },
    { id: "how-it-works", label: "How it works" },
    { id: "self-hosted-vs-managed", label: "Self-hosted vs managed" },
    { id: "common-questions", label: "Common questions" },
  ];

  return (
    <PublicSite className={styles.page} data-page="agent-detail">
      <StructuredData schema={schema} />
      <main className={styles.main} id="main-content">
        <Breadcrumbs items={[{ label: "Agents", href: "/agents" }, { label: agent.name }]} />
        <header className={styles.articleHeader}>
          <div>
            <span className={styles.eyebrow}>{agent.vendor}</span>
            <h1>{entry.h1}</h1>
            <p>{entry.subhead}</p>
            <div className={agentStyles.actions}>
              <Link href={deployHref} className={styles.button}>
                Deploy {agent.name} <ArrowUpRight size={20} aria-hidden="true" />
              </Link>
              <Link href={PRICING_HREF} className={agentStyles.textLink}>
                See pricing <ArrowUpRight size={16} aria-hidden="true" />
              </Link>
            </div>
          </div>
          <EditorialArt number={String(position).padStart(2, "0")} label={`${agent.name} on Hivra`} />
        </header>
        <div className={styles.articleLayout}>
          <ArticleNavigation items={contents} />
          <div className={styles.articleBody}>
            <section id="overview" className={styles.detailIntro}>
              {entry.longDescription.map((paragraph, index) => (
                <p key={index}>{paragraph}</p>
              ))}
            </section>
            <section id="what-you-get" className={styles.included}>
              <h2>What you get</h2>
              <ul>
                {entry.heroBullets.map((bullet) => (
                  <li key={bullet}>
                    <CheckCircle size={16} aria-hidden="true" />
                    {bullet}
                  </li>
                ))}
              </ul>
            </section>
            <section id="how-it-works">
              <h2>How it works</h2>
              <ol className={agentStyles.steps}>
                {entry.howItWorks.map((step, index) => (
                  <li key={step.title}>
                    <span className={agentStyles.stepNumber} aria-hidden="true">{String(index + 1).padStart(2, "0")}</span>
                    <span>
                      <strong>{step.title}</strong>
                      {step.detail}
                    </span>
                  </li>
                ))}
              </ol>
            </section>
            <section id="self-hosted-vs-managed">
              <h2>Self-hosted vs managed, honestly</h2>
              <ul className={agentStyles.compare}>
                {entry.vsSelfHosted.map((point) => (
                  <li key={point}>{point}</li>
                ))}
              </ul>
            </section>
            <div id="common-questions">
              <EditorialQuestions questions={entry.faqs} />
            </div>
            <p className={agentStyles.note}>{entry.affiliation}</p>
          </div>
        </div>
        <section className={styles.cta}>
          <div>
            <h2>Run {agent.name} <strong>24/7.</strong></h2>
            <p>From $9.99/mo for 2 vCPU and 4 GB RAM. Paid plans are never paused for inactivity. 7-day money-back guarantee on card payments.</p>
          </div>
          <div className={agentStyles.actions}>
            <Link href={deployHref} className={styles.button}>
              Deploy {agent.name} <ArrowUpRight size={20} aria-hidden="true" />
            </Link>
            <Link href={PRICING_HREF} className={agentStyles.textLink}>
              See pricing <ArrowUpRight size={16} aria-hidden="true" />
            </Link>
          </div>
        </section>
        <EditorialRelated
          title="Related"
          links={[
            ...entry.relatedBlogSlugs.map((blogSlug) => ({ label: `Blog: ${relatedBlogTitle(blogSlug)}`, href: `/blog/${blogSlug}` })),
            ...AGENT_SEO_ENTRIES.filter((other) => other.slug !== entry.slug).flatMap((other) => {
              const otherAgent = getAgent(other.slug);
              return otherAgent ? [{ label: `${otherAgent.name} on Hivra`, href: `/agents/${other.slug}` }] : [];
            }),
            { label: "All agents", href: "/agents" },
          ]}
        />
      </main>
    </PublicSite>
  );
}
