/**
 * Makes the audit browser look like a browser to posthog-js.
 *
 * ── WHY THIS EXISTS ────────────────────────────────────────────────────────
 *
 * posthog-js silently DROPS every `capture()` from anything it thinks is a bot.
 * In 1.318.2 (posthog-core.ts):
 *
 *     capture(event, props, opts) {
 *       if (!this.__loaded || !this.persistence || !this._requestQueue) return
 *       if (!this.is_capturing()) return                        // <- consent gate
 *       const isBot = !this.config.opt_out_useragent_filter && this._is_bot()
 *       if (isBot && !this.config.__preview_capture_bot_pageviews) return   // <- HERE
 *       ...
 *     }
 *
 * and `_is_bot()` -> `isLikelyBot(navigator)`:
 *
 *     if (navigator.userAgent matches the blocklist) return true   // 'headlesschrome'
 *     if (navigator.userAgentData.brands matches the blocklist) return true
 *     return !!navigator.webdriver                                 // <- always true under CDP
 *
 * A stock Playwright context trips ALL THREE. The return is silent: no throw, no
 * console warning, no network request. Everything OUTSIDE that gate still works
 * — remote config (`/p/array/<token>/config.js`), feature flags (`/p/flags/`),
 * and the `ph_<token>_posthog` persistence write all succeed — which is exactly
 * why this looked like a broken analytics KEY rather than a bot filter.
 *
 * Measured on canary 2026-07-08, same flow, only these signals differing:
 *
 *     stock Playwright   ->  0 ingest POSTs,  0 events   (4x /p/flags/ succeed)
 *     signals neutralized->  5 ingest POSTs, 13 events   ($identify, $pageview,
 *                            signup_completed, welcome_persona_selected,
 *                            welcome_agent_type_selected, paywall_viewed, …)
 *
 * ── WHY WE FIX THE HARNESS, NOT THE APP ────────────────────────────────────
 *
 * posthog exposes `opt_out_useragent_filter: true` to disable the bot filter
 * globally. Setting it would let REAL crawler traffic into the funnel forever so
 * that a test could pass. The filter is correct; the audit is the thing lying
 * about being a bot, and it is legitimately simulating a human first run. So the
 * lie is confined to the audit browser.
 *
 * ── GOTCHA ─────────────────────────────────────────────────────────────────
 *
 * Overriding the context `userAgent` is NOT sufficient. UA Client Hints
 * (`navigator.userAgentData.brands`) are generated by Chromium independently of
 * the UA string and still report `HeadlessChrome`; posthog checks brands BEFORE
 * it checks `webdriver`. The brands getter also cannot be shadowed reliably on
 * the NavigatorUAData instance — the whole `userAgentData` accessor has to be
 * replaced on `Navigator.prototype`.
 */
import type { Browser, BrowserContext } from '@playwright/test';

/** Chromium's headless UA token, and the blocklist entry posthog matches on. */
const HEADLESS_TOKEN = /HeadlessChrome/g;

/**
 * The same UA the browser would send, minus the `Headless` marker. Derived at
 * runtime rather than hardcoded so it stays correct across Chromium bumps and
 * across the macOS-dev / Linux-CI platform split.
 */
export function humanizeUserAgent(userAgent: string): string {
  return userAgent.replace(HEADLESS_TOKEN, 'Chrome');
}

/** Read the browser's default UA string without assuming a platform. */
export async function defaultUserAgent(browser: Browser): Promise<string> {
  const context = await browser.newContext();
  try {
    const page = await context.newPage();
    return await page.evaluate(() => navigator.userAgent);
  } finally {
    await context.close();
  }
}

/**
 * Browser-context options that make posthog's UA blocklist miss. Merge into the
 * `browser.newContext()` call — the UA must be set at context creation, it
 * cannot be changed afterwards.
 */
export async function humanBrowserContextOptions(
  browser: Browser,
): Promise<{ userAgent: string }> {
  return { userAgent: humanizeUserAgent(await defaultUserAgent(browser)) };
}

/**
 * Neutralize the two bot signals that survive a UA override: `navigator.webdriver`
 * and the UA-Client-Hints brand list. Must be called BEFORE the first navigation
 * (addInitScript runs on every document ahead of page scripts).
 */
export async function applyHumanBrowserSignals(context: BrowserContext): Promise<void> {
  await context.addInitScript(() => {
    // 1. CDP sets this on every automated Chromium. posthog reads it last, so it
    //    alone is enough to drop every event even with a perfect UA.
    Object.defineProperty(Navigator.prototype, 'webdriver', {
      get: () => false,
      configurable: true,
    });

    // 2. UA-CH brands are NOT covered by the context userAgent override.
    //    Replacing the whole accessor on Navigator.prototype is what actually
    //    wins the property lookup (shadowing `brands` on the instance does not).
    //
    //    Typed structurally: the ambient `NavigatorUAData` that happens to be in
    //    scope (from @mux/playback-core) omits getHighEntropyValues, and this
    //    body is serialized to the browser anyway, so the DOM lib buys nothing.
    type UAData = {
      brands?: Array<{ brand: string; version: string }>;
      mobile?: boolean;
      platform?: string;
      getHighEntropyValues?: (hints: string[]) => Promise<unknown>;
    };
    try {
      const real = (navigator as unknown as { userAgentData?: UAData }).userAgentData;
      if (real?.brands) {
        const brands = real.brands.map((b) =>
          /headless/i.test(b.brand) ? { brand: 'Google Chrome', version: b.version } : b,
        );
        const patched: UAData & { toJSON: () => unknown } = {
          brands,
          mobile: real.mobile,
          platform: real.platform,
          // Forwarded, not dropped: other page scripts (Clerk, GTM) may call it,
          // and a missing method would throw where the real one would not.
          getHighEntropyValues: (hints: string[]) =>
            real.getHighEntropyValues
              ? real.getHighEntropyValues(hints)
              : Promise.resolve({}),
          toJSON: () => ({ brands, mobile: real.mobile, platform: real.platform }),
        };
        Object.defineProperty(Navigator.prototype, 'userAgentData', {
          get: () => patched,
          configurable: true,
        });
      }
    } catch {
      // UA-CH unavailable (non-secure context) — the UA + webdriver overrides
      // above already carry the bot check on their own.
    }
  });
}
