import React from 'react';

export const STYLES: Record<string, React.CSSProperties> = {
  // Page
  pageContainer: {
    maxWidth: 720,
    margin: "1rem auto 5rem",
    padding: "clamp(1rem, 4vw, 3rem)",
    // The shell zeroes --dashboard-page-safe-top under its mobile header, which
    // already clears the notch; routes without that header keep the inset.
    paddingTop: "calc(var(--dashboard-page-safe-top, env(safe-area-inset-top, 0px)) + clamp(1rem, 4vw, 3rem))",
  },
  loadingContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    flex: 1,
  },

  // Header
  header: {
    textAlign: "center" as const,
    marginBottom: "clamp(1.5rem, 6vw, 4rem)",
    scrollMarginTop: "1rem",
  },
  headerBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 16px",
    border: "1px solid color-mix(in srgb, var(--gold-leaf) 30%, transparent)",
    background: "color-mix(in srgb, var(--gold-leaf) 5%, transparent)",
    borderRadius: 0,
    marginBottom: "1.5rem",
  },
  headerBadgeDot: {
    width: 4,
    height: 4,
    background: "var(--gold-leaf)",
    display: "inline-block",
    boxShadow: "0 0 10px var(--gold-leaf)",
    borderRadius: 0,
  },
  headerBadgeText: {
    fontSize: 11,
    textTransform: "uppercase" as const,
    letterSpacing: "0.25em",
    color: "var(--gold-leaf)",
    fontWeight: 700,
  },
  headerTitle: {
    fontSize: "clamp(2.5rem, 5vw, 3.5rem)",
    lineHeight: 1.1,
    fontWeight: 300,
    marginBottom: "1.25rem",
  },
  headerSubtitle: {
    fontSize: "1.05rem",
    lineHeight: 1.6,
    color: "var(--text-secondary)",
    maxWidth: 500,
    margin: "0 auto",
  },

  // Page-level banners (success / error). WelcomeFlow referenced these keys
  // before they existed — the error banner rendered completely unstyled and
  // was easy to miss, which fed the deploy-failure rageclicks.
  successBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    border: "1px solid rgba(22,163,74,0.4)",
    background: "rgba(22,163,74,0.08)",
    padding: "12px 16px",
    marginBottom: "1.5rem",
  },
  errorBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    border: "1px solid rgba(220,38,38,0.4)",
    background: "rgba(220,38,38,0.06)",
    padding: "12px 16px",
    marginBottom: "1.5rem",
  },

  // Plan Layout
  featuredSection: {
    position: "relative" as const,
    zIndex: 1,
  },
  // Alternatives header
  alternativesHeader: {
    display: "flex",
    alignItems: "center",
    gap: "1.5rem",
    marginBottom: "2rem",
    opacity: 0.4,
  },
  line: {
    flex: 1,
    height: 1,
    background: "var(--etched-border)",
  },
  alternativesLabel: {
    fontSize: 9,
    textTransform: "uppercase" as const,
    letterSpacing: "0.2em",
    fontWeight: 700,
    whiteSpace: "nowrap" as const,
  },

  // Selected Plan Card
  selectedPlanCard: {
    padding: "3rem",
    position: "relative" as const,
  },
  selectedPlanGoldBar: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    background: "var(--gold-leaf)",
    borderTopLeftRadius: "24px",
    borderTopRightRadius: "24px",
  },
  selectedPlanHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "2.5rem",
  },
  selectedPlanLabel: {
    fontSize: 10,
    textTransform: "uppercase" as const,
    letterSpacing: "0.2em",
    opacity: 0.5,
    fontWeight: 700,
  },
  selectedPlanName: {
    fontSize: "2.5rem",
    fontWeight: 700,
    marginTop: 6,
  },
  selectedPlanPrice: {
    display: "flex",
    alignItems: "baseline",
    gap: 4,
  },
  selectedPlanAmount: {
    fontSize: "3rem",
    fontWeight: 700,
    lineHeight: 1,
  },
  selectedPlanPeriod: {
    fontSize: 12,
    opacity: 0.45,
    textTransform: "uppercase" as const,
  },

  // Specs
  specsGrid: {
    display: "flex",
    gap: "1rem",
    marginBottom: "2.5rem",
    padding: "1.5rem",
    background: "color-mix(in srgb, var(--ink-black) 4%, transparent)",
    borderRadius: 0,
  },
  specItem: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  specLabel: {
    fontSize: 9,
    textTransform: "uppercase" as const,
    letterSpacing: "0.2em",
    opacity: 0.4,
    fontWeight: 700,
  },
  specValue: {
    fontSize: 14,
    fontWeight: 700,
  },

  // Features
  featureList: {
    listStyle: "none",
    padding: 0,
    margin: "0 0 3rem 0",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1rem",
  },
  featureItem: {
    fontSize: 13,
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    lineHeight: 1.4,
  },

  // Primary Button
  primaryButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: "16px 24px",
    background: "var(--ink-black)",
    color: "var(--bg-surface)",
    border: "none",
    gap: 10,
    fontFamily: "var(--font-mono), monospace",
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.1em",
    cursor: "pointer",
  },

  // Toggle plans
  togglePlansButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    padding: "12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontFamily: "var(--font-mono), monospace",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.1em",
    opacity: 0.5,
    marginBottom: "1rem",
  },

  // Plans grid
  plansGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "1rem",
    marginBottom: "1.5rem",
  },
  planCard: {
    position: "relative" as const,
    padding: "1.5rem",
    cursor: "pointer",
    textAlign: "left" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.5rem",
  },
  planPopularBadge: {
    fontSize: 8,
    textTransform: "uppercase" as const,
    letterSpacing: "0.15em",
    padding: "3px 8px",
    borderRadius: 0,
    background: "var(--gold-leaf)",
    color: "var(--ink-black)",
    fontWeight: 700,
    alignSelf: "flex-start",
  },
  planCardName: {
    fontSize: "1.1rem",
    fontWeight: 700,
    margin: 0,
  },
  planCardPrice: {
    display: "flex",
    alignItems: "baseline",
    gap: 4,
  },
  planCardPopularBadge: {
    fontSize: 8,
    textTransform: "uppercase" as const,
    letterSpacing: "0.15em",
    padding: "3px 8px",
    borderRadius: 0,
    background: "var(--gold-leaf)",
    color: "var(--ink-black)",
    fontWeight: 700,
    alignSelf: "flex-start",
  },
  planCardSpecs: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.5rem",
    marginTop: "0.5rem",
  },
  gridSpecRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    paddingTop: "0.5rem",
    borderTop: "1px dashed var(--etched-border)",
  },
  gridSpecLabel: {
    fontSize: 9,
    textTransform: "uppercase" as const,
    letterSpacing: "0.15em",
    opacity: 0.5,
    fontWeight: 700,
    fontFamily: "var(--font-mono), monospace",
  },
  gridSpecValue: {
    fontSize: 11,
    fontWeight: 700,
    fontFamily: "var(--font-mono), monospace",
  },

  // Guarantee
  guarantee: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "12px 20px",
    borderRadius: 0,
    border: "1px solid color-mix(in srgb, var(--ink-black) 8%, transparent)",
    background: "color-mix(in srgb, var(--ink-black) 2%, transparent)",
  },
  guaranteeText: {
    fontSize: 10,
    textTransform: "uppercase" as const,
    letterSpacing: "0.1em",
    opacity: 0.5,
    fontWeight: 600,
  },

  // Deploy Card
  deployCard: {
    padding: "clamp(1rem, 4vw, 2.5rem)",
    position: "relative" as const,
    marginBottom: "2rem",
    zIndex: 10,
  },
  deployCardGoldBar: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    background: "var(--gold-leaf)",
    borderTopLeftRadius: "2px",
    borderTopRightRadius: "2px",
  },

  // Step indicator
  // Wraps whole steps onto a second line on narrow phones instead of
  // breaking each label across two lines.
  deployStepIndicator: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignItems: "center",
    gap: "clamp(0.5rem, 2vw, 1rem)",
    rowGap: 8,
    marginBottom: "2rem",
    padding: "clamp(0.75rem, 3vw, 1rem)",
    background: "color-mix(in srgb, var(--ink-black) 4%, transparent)",
    borderRadius: 0,
  },
  deployStepDone: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontFamily: "var(--font-mono), monospace",
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "#16a34a",
  },
  deployStepDivider: {
    flex: 1,
    height: 1,
    background: "color-mix(in srgb, var(--ink-black) 10%, transparent)",
  },
  deployStepCurrent: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontFamily: "var(--font-mono), monospace",
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "var(--ink-black)",
  },

  // Form fields
  fieldGroup: {
    marginBottom: "1.5rem",
  },
  fieldLabel: {
    display: "block",
    fontSize: 10,
    textTransform: "uppercase" as const,
    letterSpacing: "0.2em",
    fontWeight: 700,
    marginBottom: 8,
    opacity: 0.7,
  },
  textInput: {
    width: "100%",
    border: "1px solid color-mix(in srgb, var(--ink-black) 20%, transparent)",
    borderRadius: 0,
    padding: "12px 14px",
    fontSize: 13,
    fontFamily: "var(--font-mono), monospace",
    background: "color-mix(in srgb, var(--bg-surface) 50%, transparent)",
    outline: "none",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    boxSizing: "border-box" as const,
  },

  // Provider grid
  providerGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "0.5rem",
  },
  providerButton: {
    position: "relative" as const,
    padding: "0.75rem",
    border: "1px solid color-mix(in srgb, var(--ink-black) 10%, transparent)",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  providerDot: {
    width: 6,
    height: 6,
    background: "var(--ink-black)",
    borderRadius: "50%",
  },

  // Skip
  skipButton: {
    display: "block",
    width: "100%",
    textAlign: "center" as const,
    padding: "14px",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 12,
    color: "var(--text-muted)",
    fontFamily: "inherit",
    marginTop: "0.5rem",
    borderRadius: 0,
  },
  skipButtonHover: {
    background: "color-mix(in srgb, var(--ink-black) 4%, transparent)",
  },

  // Next steps
  nextStepsCard: {
    padding: "1.5rem",
  },
  nextStepsLabel: {
    fontSize: 11,
    textTransform: "uppercase" as const,
    letterSpacing: "0.2em",
    opacity: 0.5,
    fontWeight: 700,
    marginBottom: "1rem",
    display: "block",
  },
  nextStepsGrid: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.75rem",
  },
  nextStepItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },

  // Deploying state
  deployingCard: {
    border: "1px solid var(--etched-border)",
    background: "var(--bg-surface)",
    borderRadius: 0,
    padding: "clamp(1.5rem, 4vw, 3rem)",
    margin: "clamp(1rem, 4vh, 2.5rem) auto",
    width: "min(1120px, calc(100% - clamp(2rem, 7vw, 5rem)))",
    minHeight: "min(680px, calc(100dvh - 7rem))",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 320px), 1fr))",
    gap: "clamp(1.5rem, 4vw, 3rem)",
    alignItems: "stretch",
    boxShadow: "0 18px 42px rgba(0,0,0,0.18)",
  },
  // No pane min-height: side by side the card's min-height stretches both
  // panes; stacked on a phone a fixed floor pushed the live timeline below
  // the fold.
  deployingHeroPane: {
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "center",
    minWidth: 0,
  },
  deployingOperationsPane: {
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "center",
    gap: "1.35rem",
    minWidth: 0,
  },
  deployingStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    marginBottom: "1.8rem",
  },
  deployingIconWrap: {
    width: 72,
    height: 72,
    border: "1px solid var(--gold-leaf)",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--bg-surface)",
    boxShadow: "none",
  },
  deployingKicker: {
    fontSize: 10,
    textTransform: "uppercase" as const,
    letterSpacing: "0.2em",
    color: "var(--gold-leaf)",
    fontWeight: 700,
  },
  deployingTitle: {
    fontSize: "2.12rem",
    lineHeight: 1.05,
    fontWeight: 300,
    marginBottom: "1rem",
    color: "var(--ink-black)",
    maxWidth: 500,
    // Long agent names have no spaces to break at.
    overflowWrap: "anywhere" as const,
  },
  deployingSubtitle: {
    fontSize: "1rem",
    lineHeight: 1.7,
    color: "var(--text-secondary)",
    maxWidth: 520,
    margin: "0 0 2rem",
    overflowWrap: "anywhere" as const,
  },
  // Cells draw their own 1px outlines across a 1px gap, so the dividers stay
  // correct however auto-fit wraps the cells.
  deployingStatsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 120px), 1fr))",
    gap: 1,
    padding: 1,
  },
  deployingStatCell: {
    minWidth: 0,
    padding: "1rem",
    outline: "1px solid var(--etched-border)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  deployingStatLabel: {
    fontSize: 11,
    textTransform: "uppercase" as const,
    letterSpacing: "0.16em",
    opacity: 0.5,
    fontWeight: 700,
  },
  deployingStatValue: {
    fontSize: 14,
    lineHeight: 1.25,
    fontWeight: 700,
    color: "var(--ink-black)",
    overflowWrap: "anywhere" as const,
  },
  deployingSectionHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "1rem",
    paddingBottom: "1.1rem",
    borderBottom: "1px solid var(--etched-border)",
  },
  deployingSectionLabel: {
    fontSize: 10,
    textTransform: "uppercase" as const,
    letterSpacing: "0.18em",
    fontWeight: 700,
    color: "var(--ink-black)",
  },
  deployingSectionCopy: {
    margin: "0.45rem 0 0",
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  },
  deployingEtaPill: {
    flexShrink: 0,
    padding: "0.55rem 0.75rem",
    border: "1px solid var(--gold-leaf)",
    color: "var(--gold-leaf)",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase" as const,
  },
  deployingSteps: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.85rem",
  },
  deployingStep: {
    display: "grid",
    gridTemplateColumns: "42px minmax(0, 1fr) 20px",
    alignItems: "center",
    gap: "0.85rem",
    padding: "1rem 0",
    borderBottom: "1px solid var(--etched-border)",
  },
  deployingStepIcon: {
    width: 42,
    height: 42,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid var(--gold-leaf)",
    color: "var(--gold-leaf)",
    background: "var(--bg-surface)",
  },
  deployingStepBody: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  deployingStepLabel: {
    fontSize: 11,
    textTransform: "uppercase" as const,
    letterSpacing: "0.16em",
    opacity: 0.52,
    fontWeight: 700,
  },
  deployingStepTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--ink-black)",
    overflowWrap: "anywhere" as const,
  },
  deployingStepDetail: {
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere" as const,
  },
  deployingStepIndex: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "var(--gold-leaf)",
    opacity: 0.7,
    textAlign: "right" as const,
  },
  deployingSecurityPanel: {
    paddingTop: "0.35rem",
  },
  deployingSecurityHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.65rem",
    marginBottom: "0.9rem",
    color: "var(--gold-leaf)",
  },
  deployingSecurityList: {
    listStyle: "none",
    margin: 0,
    padding: "0.9rem 0 0",
    borderTop: "1px solid var(--etched-border)",
    display: "grid",
    gap: "0.65rem",
  },
  deployingSecurityItem: {
    display: "grid",
    gridTemplateColumns: "84px minmax(0, 1fr)",
    alignItems: "baseline",
    gap: "0.85rem",
  },
  deployingSecurityItemLabel: {
    fontSize: 11,
    textTransform: "uppercase" as const,
    letterSpacing: "0.16em",
    fontWeight: 700,
    opacity: 0.55,
    color: "var(--ink-black)",
  },
  deployingSecurityItemDetail: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere" as const,
  },
};
