export function buildInstanceUpdateReportUrl(params: {
  instanceId: string;
  dashboardUrl?: string;
}): string {
  const trimmed = params.dashboardUrl?.trim() || process.env.NEXT_PUBLIC_APP_URL?.trim() || "https://hivra.cloud";
  const baseUrl = trimmed.replace(/\/$/, "");
  return `${baseUrl}/api/instances/${encodeURIComponent(params.instanceId)}/update-report`;
}

export function buildInstanceUpdateReporterShell(params: {
  instanceId: string;
  dashboardUrl?: string;
  apiServerKey?: string;
  runType: "manual" | "scheduled";
}): string {
  void params.dashboardUrl;
  void params.apiServerKey;
  const reportPath = `/api/u/${encodeURIComponent(params.instanceId)}`;

  // Status/runType are emitted by fixed script call sites; only the free-form reason needs URL encoding here.
  // Extract HERMES_DASHBOARD_URL / API_SERVER_KEY from the box .env by scanning the
  // WHOLE file and taking the first match (`| head -1`) — do NOT use `sed ...;q`: the
  // `q` quits after line 1, but the generated .env (buildWebUIComposeEnv) puts a
  // "# Generated by Hermes Deploy" comment on line 1 with the keys further down, so
  // `;q` reads empty for both keys and the callback silently no-ops (zero telemetry).
  return `ru(){ command -v curl>/dev/null 2>&1||return 0; [ -f .env ]||return 0; d=$(sed -n 's/^HERMES_DASHBOARD_URL=//p' .env | head -1); t=$(sed -n 's/^API_SERVER_KEY=//p' .env | head -1); [ -n "$d" ]&&[ -n "$t" ]||return 0; curl -fsSGm10 -H "Authorization: Bearer $t" --data-urlencode "r=$2" "\${d%/}${reportPath}?s=$1&t=${params.runType}">/dev/null 2>&1||echo W >&2; }`;
}
