// Persisted signal-cli daemon for the Hermes Signal platform.
//
// The agent's Signal adapter (gateway/platforms/signal.py in
// vanilla-hermes-agent) needs an external signal-cli daemon serving
// SIGNAL_HTTP_URL inside the gateway container's network namespace.
// signal-cli is a Java app published only as a GitHub release tarball — it is
// not in apt, and the agent containers run as uid 1024 with NO sudo in prod.
// When a tenant's agent apt-installed a JRE into the ephemeral container
// layer, the next image-update recreate silently wiped Java and the
// integration died with "JAVA_HOME is set to an invalid directory"
// (a prior disposable verification run), and any in-container "reinstall it" fallback
// no-ops without sudo.
//
// This script therefore installs the JRE and signal-cli into the PERSISTED
// webui-state volume ($HERMES_HOME) and keeps account data there too, so a
// container recreate can never break the integration again. The
// gateway-supervisor (buildWebUICompose) spawns it when SIGNAL_ACCOUNT +
// SIGNAL_HTTP_URL are configured and the URL points at loopback, and respawns
// it with a 60s backoff if it exits. The supervisor skips spawning when
// something already answers the health URL, so boxes with a legacy in-volume
// watchdog (the manual incident fix) or a tenant-run daemon stay untouched.

// Bump these TOGETHER: each signal-cli release is compiled for a specific
// Java major (0.14.x ships class-file 69 bytecode = Java 25). Running it on
// an older JRE throws UnsupportedClassVersionError at startup. Both are
// overridable per-instance via .env (SIGNAL_CLI_VERSION / SIGNAL_JRE_MAJOR)
// for emergency pins without a dashboard redeploy.
export const WEBUI_SIGNAL_CLI_VERSION = "0.14.4.1";
export const WEBUI_SIGNAL_JRE_MAJOR = "25";

// Where the compose file bind-mounts the script inside the gateway container
// (read-only, staged into the instance dir by buildWebUIBootstrapScript).
// Deliberately outside $HERMES_HOME: the script must always be the
// builder-fresh copy, never a stale persisted one.
export const WEBUI_SIGNAL_DAEMON_CONTAINER_PATH = "/opt/hermes-platform/signal-daemon.sh";

// POSIX sh (the agent image's /bin/sh is dash). Runs as uid 1024. Must never
// hardcode the container home dir — it has changed before
// (/home/hermeswebui -> /home/hermes); everything derives from $HERMES_HOME.
export function buildWebUISignalDaemonScript(): string {
  return `#!/bin/sh
# Hermes platform: persisted signal-cli daemon (bootstrap + run).
# Spawned and supervised by the gateway-supervisor; do not run two copies —
# the daemon exits if the port is already bound. Logs land in
# $HERMES_HOME/logs/signal-cli.log. Generated by Hermes Deploy; local edits
# are overwritten on every instance update.
set -eu

HERMES_DIR="\${HERMES_HOME:-\${HOME}/.hermes}"

SIGNAL_CLI_VERSION="\${SIGNAL_CLI_VERSION:-${WEBUI_SIGNAL_CLI_VERSION}}"
SIGNAL_JRE_MAJOR="\${SIGNAL_JRE_MAJOR:-${WEBUI_SIGNAL_JRE_MAJOR}}"

JRE_DIR="$HERMES_DIR/jre"
CLI_DIR="$HERMES_DIR/signal-cli"
DATA_DIR="$HERMES_DIR/signal-data"
TMP_DIR="$HERMES_DIR/.signal-setup.tmp"

log() { echo "[signal-daemon] $*"; }

adoptium_arch() {
  case "$(uname -m)" in
    aarch64|arm64) echo aarch64 ;;
    *) echo x64 ;;
  esac
}

jre_ok() {
  [ -x "$JRE_DIR/bin/java" ] || return 1
  # The release file pins the exact version; only the major must match the
  # signal-cli build (wrong major = UnsupportedClassVersionError).
  grep -q "^JAVA_VERSION=\\"$SIGNAL_JRE_MAJOR[.\\"]" "$JRE_DIR/release" 2>/dev/null
}

install_jre() {
  log "installing Temurin $SIGNAL_JRE_MAJOR JRE into $JRE_DIR"
  rm -rf "$TMP_DIR" || return 1
  mkdir -p "$TMP_DIR/jre" || return 1
  curl -fsSL --retry 3 -o "$TMP_DIR/jre.tar.gz" \\
    "https://api.adoptium.net/v3/binary/latest/$SIGNAL_JRE_MAJOR/ga/linux/$(adoptium_arch)/jre/hotspot/normal/eclipse" || return 1
  tar -xzf "$TMP_DIR/jre.tar.gz" -C "$TMP_DIR/jre" --strip-components=1 || return 1
  "$TMP_DIR/jre/bin/java" -version 2>&1 | head -n 1 || return 1
  rm -rf "$JRE_DIR" || return 1
  mv "$TMP_DIR/jre" "$JRE_DIR" || return 1
  rm -rf "$TMP_DIR"
}

cli_ok() {
  [ -x "$CLI_DIR/bin/signal-cli" ] || return 1
  [ "$(cat "$CLI_DIR/.hermes-signal-cli-version" 2>/dev/null || true)" = "$SIGNAL_CLI_VERSION" ]
}

install_cli() {
  log "installing signal-cli $SIGNAL_CLI_VERSION into $CLI_DIR"
  rm -rf "$TMP_DIR" || return 1
  mkdir -p "$TMP_DIR/cli" || return 1
  curl -fsSL --retry 3 -o "$TMP_DIR/cli.tar.gz" \\
    "https://github.com/AsamK/signal-cli/releases/download/v$SIGNAL_CLI_VERSION/signal-cli-$SIGNAL_CLI_VERSION.tar.gz" || return 1
  tar -xzf "$TMP_DIR/cli.tar.gz" -C "$TMP_DIR/cli" --strip-components=1 || return 1
  printf '%s\\n' "$SIGNAL_CLI_VERSION" > "$TMP_DIR/cli/.hermes-signal-cli-version" || return 1
  rm -rf "$CLI_DIR" || return 1
  mv "$TMP_DIR/cli" "$CLI_DIR" || return 1
  rm -rf "$TMP_DIR"
}

# Repair installs when missing or version-mismatched. When a (possibly stale)
# install already exists and the refresh download fails — offline VM, GitHub
# hiccup — fall back to the existing binaries rather than taking a working
# integration down.
if ! jre_ok; then
  if [ -x "$JRE_DIR/bin/java" ]; then
    install_jre || log "WARN: JRE refresh failed; keeping existing $JRE_DIR"
  else
    install_jre
  fi
fi
if ! cli_ok; then
  if [ -x "$CLI_DIR/bin/signal-cli" ]; then
    install_cli || log "WARN: signal-cli refresh failed; keeping existing $CLI_DIR"
  else
    install_cli
  fi
fi

mkdir -p "$DATA_DIR" "$HERMES_DIR/logs"
# Rescue account keys from an agent-led setup that used signal-cli's default
# data dir in the ephemeral container home. Without this, the first container
# recreate after such a setup forces the client to re-link their phone.
if [ ! -e "$DATA_DIR/data" ] && [ -d "\${HOME}/.local/share/signal-cli/data" ]; then
  log "migrating signal-cli account data from \${HOME}/.local/share/signal-cli"
  cp -a "\${HOME}/.local/share/signal-cli/." "$DATA_DIR/"
fi

# The adapter dials SIGNAL_HTTP_URL; the supervisor only manages loopback
# URLs, so bind 127.0.0.1 on the URL's port (default 8080).
url="\${SIGNAL_HTTP_URL:-http://127.0.0.1:8080}"
hostport="\${url#*://}"
hostport="\${hostport%%/*}"
case "$hostport" in
  *:*) port="\${hostport##*:}" ;;
  *) port=8080 ;;
esac
case "$port" in
  ''|*[!0-9]*) port=8080 ;;
esac

export JAVA_HOME="$JRE_DIR"
export PATH="$JRE_DIR/bin:$PATH"
log "starting signal-cli $SIGNAL_CLI_VERSION daemon on 127.0.0.1:$port (data: $DATA_DIR)"
exec "$CLI_DIR/bin/signal-cli" --config "$DATA_DIR" daemon --http "127.0.0.1:$port"
`;
}
