import PublicSite from "@/components/public-site/PublicSite";
import styles from "../../components/public-editorial/secondary-site.module.css";
import type { Metadata } from "next";
import { cookies, headers } from "next/headers";

import StructuredData from "@/components/StructuredData";
import { LocaleProvider } from "@/components/i18n/LocaleProvider";
import { buildWebsiteMetadata } from "@/lib/metadata";
import { OG_IMAGE } from "@/lib/og-meta";
import { SITE_URL } from "@/lib/seo-urls";
import { LOCALE_COOKIE_NAME, resolveRequestLocale } from "@/lib/i18n";

import StatusPageContent from "@/components/status/StatusPageContent.client";

const PATH = "/status";
const TITLE = "Status: Hivra platform health";
const DESCRIPTION =
  "Live operational status of Hivra's public surfaces — website, sign-in, get-started and changelog — checked from your browser in real time.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  ...buildWebsiteMetadata({
    path: PATH,
    title: TITLE,
    description: DESCRIPTION,
    // Branded dynamic OG card generated by app/status/opengraph-image.tsx (#public-og-images).
    images: [OG_IMAGE.status],
  }),
};

const schema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
        { "@type": "ListItem", position: 2, name: "Status", item: `${SITE_URL}${PATH}` },
      ],
    },
  ],
};

async function getLandingLocale() {
  const [cookieStore, headerStore] = await Promise.all([cookies(), headers()]);
  return resolveRequestLocale({
    cookieLocale: cookieStore.get(LOCALE_COOKIE_NAME)?.value,
    acceptLanguage: headerStore.get("accept-language"),
  });
}

// Public, signed-out-accessible status page. Mirrors the /stats scaffold
// (LandingHeader + Footer + StructuredData + InteractiveBackground), but deals
// in zero account data: the live checks run client-side and read only the
// platform's own public surfaces. No auth/Clerk, no DB, no schema.
export default async function StatusPage() {
  const locale = await getLandingLocale();

  return (
    <LocaleProvider initialLocale={locale}>
      <PublicSite className={styles.livePage} data-page="status">
        <StructuredData schema={schema} />


        <div className={styles.liveContent}>
          <StatusPageContent />
        </div>

      </PublicSite>
    </LocaleProvider>
  );
}
