import PublicSite from "@/components/public-site/PublicSite";
import { Breadcrumbs, EditorialRelated } from "@/components/public-editorial/Editorial";
import styles from "../../components/public-editorial/secondary-site.module.css";
import agentStyles from "./agents.module.css";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import StructuredData from "@/components/StructuredData";
import { buildWebsiteMetadata } from "@/lib/metadata";
import { SITE_URL } from "@/lib/seo-urls";
import {
  AGENTS_HUB_AFFILIATION,
  AGENTS_HUB_DEPLOY_HREF,
  AGENT_SEO_ENTRIES,
  PRICING_HREF,
} from "@/lib/hivra/agent-seo-catalog";
import { getAgent } from "@/lib/hivra/agent-catalog";
import { BLOG_ARTICLES } from "@/lib/blog-data";

// The root layout's title template appends " | Hivra".
const PAGE_TITLE = "Deploy AI Agents: Claude Code, Codex, Hermes and More";
const PAGE_DESCRIPTION =
  "Run Claude Code, Codex, Hermes, Aeon, OpenClaw and Agent Zero on managed cloud VMs with your own sign-ins. Paid plans stay on. From $9.99/mo.";

export const metadata: Metadata = {
  title: PAGE_TITLE,
  description: PAGE_DESCRIPTION,
  ...buildWebsiteMetadata({
    path: "/agents",
    title: PAGE_TITLE,
    description: PAGE_DESCRIPTION,
    // Generated by app/agents/opengraph-image.tsx.
    images: [{ url: "/agents/opengraph-image", width: 1200, height: 630, alt: "Agents you can deploy on Hivra", type: "image/png" }],
  }),
};

const SUMMARY = [
  {
    title: "Your own sign-ins",
    body: "Claude Code uses your Anthropic account. Codex uses your ChatGPT account or OpenAI key. Hermes runs on the model key you already pay for.",
  },
  {
    title: "Stays on when you log off",
    body: "Every agent gets a private cloud VM of its own, and paid plans are never paused for inactivity. Hermes, OpenClaw and Agent Zero run on that computer, and Aeon's tasks run on your own GitHub Actions, so none of them needs an open browser. A Claude Code or Codex run you start inside tmux in the computer's Terminal tab keeps going after you close the laptop.",
  },
  {
    title: "From $9.99 a month",
    body: "2 vCPU and 4 GB RAM to start, or 4 vCPU and 8 GB for $19.99. Card payments come with a 7-day money-back guarantee.",
  },
  {
    title: "Public source",
    body: "Hivra's source is public under the Apache-2.0 license, and self-hosting is available as a preview for a single operator.",
  },
] as const;

const HUB_RELATED_BLOG_SLUGS = ["byo-api-key-explained", "cost-of-running-ai-agent"] as const;

export default function AgentsIndexPage() {
  const agents = AGENT_SEO_ENTRIES.flatMap((entry) => {
    const def = getAgent(entry.slug);
    return def ? [{ entry, def }] : [];
  });

  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ItemList",
        name: "Agents you can deploy on Hivra",
        itemListElement: agents.map(({ entry, def }, index) => ({
          "@type": "ListItem",
          position: index + 1,
          name: def.name,
          url: `${SITE_URL}/agents/${entry.slug}`,
        })),
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
          { "@type": "ListItem", position: 2, name: "Agents", item: `${SITE_URL}/agents` },
        ],
      },
    ],
  };

  return (
    <PublicSite className={styles.page} data-page="agents">
      <StructuredData schema={schema} />
      <main className={styles.main} id="main-content">
        <Breadcrumbs items={[{ label: "Agents" }]} />
        <header className={styles.masthead}>
          <span className={styles.eyebrow}>Agents on Hivra</span>
          <h1>Agents you can deploy <strong>today.</strong></h1>
          <p>
            Every agent below runs on a private cloud VM of its own. You sign in with your own accounts, and Hivra
            handles the provisioning. On a paid plan the machine stays on after you log off.
          </p>
        </header>

        <div className={styles.introGrid}>
          {SUMMARY.map(({ title, body }) => (
            <div key={title}>
              <h2>{title}</h2>
              <p>{body}</p>
            </div>
          ))}
        </div>
        <div className={`${styles.directoryAction} ${agentStyles.actions}`}>
          <Link href={AGENTS_HUB_DEPLOY_HREF} className={styles.button}>
            Start now <ArrowUpRight size={20} aria-hidden="true" />
          </Link>
          <Link href={PRICING_HREF} className={agentStyles.textLink}>
            See pricing <ArrowUpRight size={16} aria-hidden="true" />
          </Link>
        </div>

        <div className={styles.indexHead}>
          <h2>Every agent gets its own computer</h2>
        </div>
        <div className={`${styles.directory} ${agentStyles.agentDirectory}`}>
          {agents.map(({ entry, def }, index) => (
            <Link key={entry.slug} href={`/agents/${entry.slug}`}>
              <span>{String(index + 1).padStart(2, "0")}</span>
              <h2>{def.name}</h2>
              <div>
                <h3>{entry.cardSummary}</h3>
                <div className={agentStyles.cardFooter}>
                  <span className={agentStyles.vendor}>{def.vendor}</span>
                  <span className={styles.readLink}>
                    Run {def.name} in the cloud <ArrowUpRight size={20} aria-hidden="true" />
                  </span>
                </div>
              </div>
            </Link>
          ))}
        </div>

        <section className={styles.cta}>
          <div>
            <h2>Pick an agent. <strong>Give it a computer.</strong></h2>
            <p>From $9.99/mo for 2 vCPU and 4 GB RAM. 7-day money-back guarantee on card payments.</p>
          </div>
          <div className={agentStyles.actions}>
            <Link href={AGENTS_HUB_DEPLOY_HREF} className={styles.button}>
              Start now <ArrowUpRight size={20} aria-hidden="true" />
            </Link>
            <Link href={PRICING_HREF} className={agentStyles.textLink}>
              See pricing <ArrowUpRight size={16} aria-hidden="true" />
            </Link>
          </div>
        </section>

        <p className={agentStyles.note}>{AGENTS_HUB_AFFILIATION}</p>

        <EditorialRelated
          title="See also"
          links={[
            { label: "Every Hivra feature", href: "/features" },
            { label: "Hivra vs Self-Hosted", href: "/compare/vs-self-hosted" },
            ...HUB_RELATED_BLOG_SLUGS.flatMap((slug) =>
              BLOG_ARTICLES[slug] ? [{ label: `Blog: ${BLOG_ARTICLES[slug].title}`, href: `/blog/${slug}` }] : [],
            ),
          ]}
        />
      </main>
    </PublicSite>
  );
}
