import { spawn } from "node:child_process";
import { buildProviderGuestRuntimeProbe, parseProviderGuestRuntimeReceipt, type ProviderGuestRuntimeProbe } from "../provider-guest-runtime";
import { providerGuestBundleScopeSha256 } from "../provider-guest-bundle";
import { receiverFixture } from "./first-boot-receiver.fixtures";

const scope = { binding: receiverFixture().binding, providerServerId: "42" };
export function runtimeProbeFixture(): ProviderGuestRuntimeProbe {
  return { scope, runtime: "codex", identity: { version: 1,
    agentId: "11111111-1111-4111-8111-111111111111", operationId: "22222222-2222-4222-8222-222222222222",
    bundle: { version: 1, state: "bundle_installed", scopeSha256: providerGuestBundleScopeSha256(scope),
      bundleSha256: "a".repeat(64), provisionerVersion: "2026.08.28.1" } } };
}
const line = (receipt: unknown) => `HIVRA_PROVIDER_RUNTIME_V1 ${JSON.stringify(receipt)}\n`;
function ready() {
  const probe = runtimeProbeFixture();
  return { probe, receipt: { version: 1, ready: true, identity: probe.identity, runtime: probe.runtime, apiToken: "b".repeat(64) } };
}

it("binds a read-only recipe to the exact existing operation and scope without installing or running a worker", () => {
  const plan = buildProviderGuestRuntimeProbe(runtimeProbeFixture());
  expect(plan.script).toContain('"/var/lib/hivra/provider-install"');
  expect(plan.script).toContain('"/usr/bin/systemctl", "is-active"');
  expect(plan.script).toContain('HTTPConnection("127.0.0.1"');
  expect(plan.script).not.toMatch(/shell=True|systemd-run|os\.rename|os\.unlink|os\.chmod|https?:\/\/|tunnelToken|modelKey/);
  expect(plan.script).toContain("os.O_NOFOLLOW | os.O_NONBLOCK");
});
it("selects the standalone access service in the signed runtime probe", () => {
  const plan = buildProviderGuestRuntimeProbe({ ...runtimeProbeFixture(), accessMode: "direct-https" });
  expect(plan.accessMode).toBe("direct-https");
  expect(plan.script).toContain('"hivra-direct-access.service" if EXPECTED["accessMode"] == "direct-https"');
});
it("runs the actual generated recipes and filesystem guards without network or systemd calls", async () => {
  const scripts = Object.fromEntries((["claude", "codex", "aeon", "openclaw", "agent-zero"] as const)
    .flatMap(runtime => [[runtime, buildProviderGuestRuntimeProbe({ ...runtimeProbeFixture(), runtime }).script],
      [runtime + "-power", buildProviderGuestRuntimeProbe({ ...runtimeProbeFixture(), runtime, captureBootId: true }).script]]));
  // spawnSync intermittently stalled this >64KiB input in Python's read-to-EOF
  // before tests began. Stream it asynchronously and await child close; retain
  // the original deadline, exact generated bytes and bounded diagnostics.
  const result = await new Promise<{ status: number | null; stdout: string; stderr: string; error: string }>(resolve => {
    const child = spawn("/usr/bin/python3", ["-I", "-B", "scripts/test-provider-runtime-probe.py"], {
      timeout: 10_000, killSignal: "SIGKILL", env: { PATH: "/usr/bin:/bin", LANG: "C", NODE_ENV: "test" },
    });
    let stdout = "", stderr = "", error = "";
    const collect = (channel: "stdout" | "stderr", data: Buffer) => {
      if (Buffer.byteLength(stdout) + Buffer.byteLength(stderr) + data.length > 65_536) {
        error = "probe output exceeded limit"; child.kill("SIGKILL"); return;
      }
      if (channel === "stdout") stdout += data.toString(); else stderr += data.toString();
    };
    child.stdout.on("data", data => collect("stdout", data));
    child.stderr.on("data", data => collect("stderr", data));
    child.on("error", err => { error = err.message; });
    child.stdin.on("error", err => { error = err.message; });
    child.on("close", status => resolve({ status, stdout, stderr, error }));
    child.stdin.end(JSON.stringify(scripts));
  });
  expect({ status: result.status, stdout: result.stdout, error: result.error || (result.status === 0 ? "" : result.stderr) })
    .toEqual({ status: 0, stdout: "", error: "" });
  expect(result.stderr).toContain("Ran 7 tests");
}, 12_000);
it("accepts only a matching readiness receipt; unsuccessful observations never carry a bearer", () => {
  const { probe, receipt } = ready();
  expect(parseProviderGuestRuntimeReceipt(line(receipt), probe)).toEqual(receipt);
  const pending = { version: 1, ready: false, identity: probe.identity, runtime: probe.runtime, reason: "runtime_unavailable" };
  expect(parseProviderGuestRuntimeReceipt(line(pending), probe)).toEqual(pending);
  expect(() => parseProviderGuestRuntimeReceipt(line({ ...pending, apiToken: receipt.apiToken }), probe)).toThrow("Invalid provider runtime receipt");
});
it.each(["scope", "agent", "operation", "bundle", "runtime", "secret", "extra", "version"])("rejects changed %s without returning a credential", field => {
  const { probe, receipt } = ready();
  const changed = structuredClone(receipt);
  if (field === "scope") changed.identity.bundle.scopeSha256 = "f".repeat(64);
  if (field === "agent") changed.identity.agentId = probe.identity.operationId;
  if (field === "operation") changed.identity.operationId = probe.identity.agentId;
  if (field === "bundle") changed.identity.bundle.bundleSha256 = "e".repeat(64);
  if (field === "runtime") changed.runtime = "claude";
  if (field === "secret") changed.apiToken = "PRIVATE_MALFORMED_TOKEN";
  if (field === "extra") Object.assign(changed, { modelKey: "PRIVATE_KEY" });
  if (field === "version") changed.version = 2;
  expect(() => parseProviderGuestRuntimeReceipt(line(changed), probe)).toThrow("Invalid provider runtime receipt");
});
it.each(["prefix", "line", "crlf", "oversized", "unterminated"])("rejects %s output framing", field => {
  const { probe, receipt } = ready();
  const output = line(receipt);
  const bad = field === "prefix" ? "log\n" + output : field === "line" ? output + output : field === "crlf" ? output.replace("\n", "\r\n")
    : field === "oversized" ? "x".repeat(4097) : output.slice(0, -1);
  expect(() => parseProviderGuestRuntimeReceipt(bad, probe)).toThrow("Invalid provider runtime receipt");
});
it("rejects unrelated or malformed input before transport", () => {
  const probe = runtimeProbeFixture(); probe.scope = { ...scope, providerServerId: "43" };
  expect(() => buildProviderGuestRuntimeProbe(probe)).toThrow("Invalid provider runtime probe");
  expect(() => buildProviderGuestRuntimeProbe({ ...runtimeProbeFixture(), runtime: "arbitrary-command" as never })).toThrow();
  expect(() => buildProviderGuestRuntimeProbe({ ...runtimeProbeFixture(), captureBootId: false as never })).toThrow();
});

it("requires explicit power observation to accept a boot identity and keeps it independent of runtime readiness", () => {
  const { probe, receipt } = ready();
  const power = { ...probe, captureBootId: true as const }, bootId = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
  expect(parseProviderGuestRuntimeReceipt(line({ ...receipt, bootId }), power)).toEqual({ ...receipt, bootId });
  expect(() => parseProviderGuestRuntimeReceipt(line({ ...receipt, bootId }), probe)).toThrow();
  expect(() => parseProviderGuestRuntimeReceipt(line(receipt), power)).toThrow();
  for (const reason of ["runtime_unavailable", "authentication_unverified", "native_unavailable"]) {
    const pending = { version: 1, ready: false, runtime: probe.runtime, identity: probe.identity, reason, bootId };
    expect(parseProviderGuestRuntimeReceipt(line(pending), power)).toEqual(pending);
    expect(() => parseProviderGuestRuntimeReceipt(line({ ...pending, bootId: undefined }), power)).toThrow();
    expect(() => parseProviderGuestRuntimeReceipt(line({ ...pending, apiToken: receipt.apiToken }), power)).toThrow();
  }
  for (const reason of ["installer_unverified", "boot_unverified"]) {
    const pending = { version: 1, ready: false, runtime: probe.runtime, identity: probe.identity, reason };
    expect(parseProviderGuestRuntimeReceipt(line(pending), power)).toEqual(pending);
    expect(() => parseProviderGuestRuntimeReceipt(line({ ...pending, bootId }), power)).toThrow();
  }
});
it.each([null, "", "boot-id", 1, "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb\n"])("rejects malformed boot identity %s", bootId => {
  const { probe, receipt } = ready();
  expect(() => parseProviderGuestRuntimeReceipt(line({ ...receipt, bootId }), { ...probe, captureBootId: true })).toThrow();
});
