import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  buildInstanceUpdateReportUrl,
  buildInstanceUpdateReporterShell,
} from "../update-status-reporting";

describe("update-status-reporting", () => {
  it("encodes instance ids in report URLs", () => {
    expect(
      buildInstanceUpdateReportUrl({
        instanceId: "inst/$() ?",
        dashboardUrl: "https://example.com/",
      })
    ).toBe("https://example.com/api/instances/inst%2F%24()%20%3F/update-report");
  });

  it("builds a shell reporter that keeps dynamic values URL-encoded and logs generic failures only", () => {
    const shell = buildInstanceUpdateReporterShell({
      instanceId: "inst/$() ?",
      runType: "manual",
    });

    expect(shell).toContain("/api/u/inst%2F%24()%20%3F");
    expect(shell).toContain('--data-urlencode "r=$2"');
    expect(shell).toContain("?s=$1&t=manual");
    expect(shell).toContain("echo W >&2");
    expect(shell).not.toContain("?s=$s&t=manual&r=$r");
    // Guard the sed `;q` regression: the key extraction must scan the whole .env
    // (`| head -1`), never quit after line 1 (`p;q`). buildWebUIComposeEnv writes a
    // comment on line 1, so `;q` would read empty values and silently drop telemetry.
    expect(shell).not.toMatch(/=\/\/p;q'/);
    expect(shell).toContain("//p' .env | head -1");
  });

  // Regression for the fleet-wide "redeploys emit no update telemetry" bug: the
  // box-side `ru` reporter must read HERMES_DASHBOARD_URL + API_SERVER_KEY by
  // scanning the whole .env. The previous `sed ...;q` quit after line 1, but
  // buildWebUIComposeEnv puts a "# Generated by Hermes Deploy" comment on line 1
  // with the keys further down, so both values came back empty and every
  // redeploy/update callback silently no-op'd. This runs the generated shell
  // against a realistic .env to prove the callback actually fires.
  it("ru() reads the dashboard URL + key from a realistic multi-line .env and fires the callback", () => {
    const dir = mkdtempSync(join(tmpdir(), "ru-reporter-"));
    try {
      // Mirrors buildWebUIComposeEnv: comment header on line 1, keys further down.
      writeFileSync(
        join(dir, ".env"),
        [
          "# Generated by Hermes Deploy — do not edit by hand",
          "HERMES_INFERENCE_PROVIDER=venice",
          "HERMES_WEBUI_DEFAULT_MODEL=venice-uncensored",
          "HERMES_DASHBOARD_URL=https://hivra.cloud",
          "API_SERVER_KEY=test-webui-pass",
          "",
        ].join("\n")
      );

      const shell = buildInstanceUpdateReporterShell({
        instanceId: "abc-123",
        runType: "scheduled",
      });

      // Shadow curl so the callback is captured instead of hitting the network.
      const harness = `${shell}
curl(){ CAPTURED="$*"; }
ru "succeeded" "completed"
printf '%s' "$CAPTURED"`;

      const captured = execFileSync("sh", ["-c", harness], {
        cwd: dir,
        encoding: "utf8",
      });

      // The callback fired (non-empty) carrying the right URL + bearer token.
      expect(captured).toContain(
        "https://hivra.cloud/api/u/abc-123?s=succeeded&t=scheduled"
      );
      expect(captured).toContain("Authorization: Bearer test-webui-pass");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("ru() stays a silent no-op when the box .env is absent", () => {
    const dir = mkdtempSync(join(tmpdir(), "ru-reporter-empty-"));
    try {
      const shell = buildInstanceUpdateReporterShell({
        instanceId: "abc-123",
        runType: "manual",
      });
      const harness = `${shell}
curl(){ CAPTURED="$*"; }
ru "succeeded" "completed"
printf '%s' "$CAPTURED"`;

      const captured = execFileSync("sh", ["-c", harness], {
        cwd: dir,
        encoding: "utf8",
      });

      expect(captured).toBe("");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
